import Link from "next/link"
// Import file "Geobal Css"
import "./globals.css"

// import fontAwosome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: 'UAF.DEV',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body>
        {/* area header */}
        <header>
          {/* area image/banner */}
          <img src="../images/logo.png" alt="Logo UTI" />

          {/* area menu */}
          <nav className="mt-5 flex justify-center">
            <Link href={"/"} className="bg-teal-700 hover:bg-teal-800 text-white rounded-full px-5 py-2.5 mr-3 w-52 text-center"> Data Mahasiswa </Link>
            <Link href={"/"} className="bg-teal-700 hover:bg-teal-800 text-white rounded-full px-5 py-2.5 ml-3 w-52 text-center"> Log Data Mahasiswa </Link>
          </nav>

        </header>

        {/* area conten */}
        <section className="m-5">
        {children}
        </section>
        

        {/* area footer */}
        <footer className="py-15X flex justify-center bg-color1 text-color3-1">
          Copyright &copy; 2024 - Umar

        </footer>
      </body>
    </html>
  )
}
